main: me.mrliam2614.ChatManager
name: ChatManager
version: 5.1.1
author: MrLiam2614
description: Make your server's chat cool!
depend: [FacilitisAPI, Vault]
softdepend: [PlaceholderAPI]
commands:
  mutechat:
    description: Mute the chat!
  socialspy:
    aliases: [sspy]
    description: check your players commands and private messages!
  chatmanager:
    aliases: [cm]
    description: Configure chatmanager in game!